indeed:
  domains:
    - it.indeed.com
    - indeed.com
  job:
    - "/viewjob"
  search:
    - "/jobs?"
    - "/q-"
    - "offerte-lavoro"
  career_page:
    - "/career/"
    - "/companies"
    - "/cmp/"
    - "/"

jooble:
  domains:
    - it.jooble.org
    - jooble.org
  job:
    - "/jdp/"
    - "/rjdp/"
  search:
    - "/lavoro-"
    - "/SearchResult"

linkedin:
  domains:
    - it.linkedin.com
    - linkedin.com
  job:
    - "/jobs/view/"
  search:
    - "/jobs/"
    - "/jobs/search"

glassdoor:
  domains:
    - www.glassdoor.it
    - glassdoor.it
    - www.glassdoor.com
    - glassdoor.com
  job:
    - "/job-listing/"
  search:
    - "/Lavoro/"
    - "/Job/"
    - "SRCH_"

randstad:
  domains:
    - www.randstad.it
    - randstad.it
  search_before_job: true
  job_all:
    - "/offerte-lavoro/"
    - "_"
  search:
    - "/offerte-lavoro/"
    - "/offerte-lavoro/s-"
    - "/page-"
    - "/offerte-lavoro/s-customer-service"
    - "/offerte-lavoro/q-"
    - "/offerte-lavoro/re-"
    - "/offerte-lavoro/ci-"

adecco:
  domains:
    - www.adecco.it
    - adecco.it
  job:
    - "/offerta/"
    - "/job-offer/"
  job_all:
    - "/lavoro/"
    - "_"
  search:
    - "/lavoro?"
    - "/lavoro/"
    - "/offerte-lavoro"
    - "/jobs?"
  career_page:
    - "/lavora-con-noi"
    - "/chi-siamo"

gigroup:
  domains:
    - www.gigroup.it
    - gigroup.it
  job:
    - "/offerte-lavoro/dettaglio-offerta/"
    - "/offerte-lavoro/job-detail/"
    - "/annunci/"
    - "/jobs/"
    - "/job/"
  search:
    - "/offerte-lavoro?"
    - "/offerte-lavoro/"
    - "/cerca-lavoro"
    - "/risultati-ricerca"
    - "/search"
  career_page:
    - "/lavora-con-noi"
    - "/candidati"
    - "/career"
    - "/chi-siamo"

jobsora:
  domains:
    - it.jobsora.com
    - jobsora.com
  search:
    - "/lavoro/"
    - "/lavoro-"
    - "/query-"

jobsavior:
  domains:
    - it.jobsavior.com
    - jobsavior.com
  search:
    - "/offerte-di-lavoro/query-"

freelancer:
  domains:
    - www.freelancer.co.it
    - freelancer.co.it
  search:
    - "/job-search/"

jobbydoo:
  domains:
    - www.jobbydoo.it
    - jobbydoo.it
  search:
    - "/lavoro-"

subito:
  domains:
    - www.subito.it
    - subito.it
  search_before_job: true
  job_all:
    - "/offerte-lavoro/"
    - ".htm"
  search:
    - "/annunci-"
    - "/offerte-lavoro"

lidl:
  domains:
    - lavoro.lidl.it
  job:
    - "/punti-vendita/"
  career_page:
    - "/annunci-di-lavoro"
    - "/lavora-con-noi"

eurospin:
  domains:
    - www.eurospin.it
    - eurospin.it
  career_page:
    - "/lavora-con-noi"

manpower:
  domains:
    - www.manpower.it
    - manpower.it
  search:
    - "/trova-lavoro"

talent:
  domains:
    - www.talent.com
    - talent.com
  job:
    - "/view?id="

jobleads:
  domains:
    - www.jobleads.com
    - jobleads.com
  job:
    - "/it/job/"

workwide:
  domains:
    - www.workwide.it
    - workwide.it
  job:
    - "/jobs/"

general_exclude_domains:
  - partitaiva.it
  - duckinformatica.it
  - ispazio.net
  - tooliamo.com
  - simonebarbone.net
  - onlinedataentryjob.com
  - terredamare.com
  - comune.napoli.it
